name: Publish dist files

on:
  push:
    branches:
      - master

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run dist-no-d-ts
    - name: Checkout or create dist branch
      run: |
        git checkout -b dist || git checkout dist
    - name: Add dist files
      run: |
        git add dist/* -f
    - name: Set git user email and name
      run: |
        git config --global user.email "2285697543@qq.com"
        git config --global user.name "BlackWhite"
    - name: Add all files to git
      run: git add .
    - name: Commit and push dist files
      run: |
        git commit -m "Add dist files"
        git push origin dist --force
