name: Publish dist files

on:
  push:
    branches:
      - master

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: rm -rf dist
    - run: mkdir dist
    - run: npm run dist-no-d-ts
    - name: 切换或创建dist分支
      run: |
        git checkout -b dist || git checkout dist
    - name: 清空dist分支
      run: git rm -r --cached .
    - name: 添加发布文件
      run: git add dist/*
    - name: 移动至根目录
      run: git mv ./dist/* ./
    - name: 操作信息
      run: |
        git config user.email "2285697543@qq.com"
        git config user.name "BlackWhite"
    - name: 推送发布文件
      run: |
        git commit -m "Add dist files"
        git push origin dist --force
